-- ==========================================================
-- SUPABASE DATABASE SCHEMA FOR EXPENSE CLAIMS & ADMINS
-- Execute this SQL code in your Supabase SQL Editor
-- Link: https://supabase.com/dashboard/project/yrbidrfhzuxmxqcboqfd/sql
-- ==========================================================

-- 1. DROP EXISTING TABLES IF THEY EXISTS (CAUTION: Removes existing data)
-- DROP TABLE IF EXISTS expense_claims;
-- DROP TABLE IF EXISTS admins;

-- 2. CREATE ADMINS TABLE
-- Stores administrative credentials for Dashboard log in
CREATE TABLE IF NOT EXISTS admins (
    email TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. CREATE EXPENSE CLAIMS TABLE
-- Stores itemized expense claims submitted by salespeople
CREATE TABLE IF NOT EXISTS expense_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id TEXT NOT NULL,
    timestamp TEXT,
    branch_name TEXT,
    salesperson_name TEXT,
    salesperson_email TEXT,
    expense_category TEXT,
    item_date TEXT,
    from_location TEXT,
    to_location TEXT,
    amount TEXT,
    attachment_link TEXT,
    item_remark TEXT,
    grand_total TEXT,
    admin_remark TEXT,
    mail_sent TEXT DEFAULT 'No',
    approved TEXT DEFAULT 'No',
    approved_timestamp TEXT,
    payment_process TEXT DEFAULT 'No',
    processed_by TEXT,
    status TEXT DEFAULT 'Pending',
    payment_release TEXT DEFAULT 'No',
    released_by TEXT,
    branch_head_email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. INSERT DEFAULT ADMIN ACCOUNT
-- To permit immediate sign in
INSERT INTO admins (email, name, password) 
VALUES ('mis.mumbai@ginzalimited.com', 'Mumbai Admin', 'admin123')
ON CONFLICT (email) DO NOTHING;

-- 5. ROW LEVEL SECURITY (RLS) POLICIES
-- Service role key automatically bypasses RLS.
-- This policy permits public/authenticated reads and writes for simplicity.
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_claims ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read and write on admins" 
ON admins FOR ALL 
USING (true) 
WITH CHECK (true);

CREATE POLICY "Allow public read and write on expense_claims" 
ON expense_claims FOR ALL 
USING (true) 
WITH CHECK (true);

-- 6. VERIFY TABLES
SELECT 'admins table exists' as status FROM information_schema.tables WHERE table_name = 'admins' LIMIT 1;
SELECT 'expense_claims table exists' as status FROM information_schema.tables WHERE table_name = 'expense_claims' LIMIT 1;
